# Site settings
title: lyk's Blog
SEOTitle: lyk's Blog
header-img: img/bg.jpg
email: grlyk02@gmail.com
description: "lyk的个人博客"
keyword: "lyk"
url: "http://grlyh.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "蒟蒻OIer"
#sidebar-avatar: /img/tou.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页
